build:
  version: "1.0"

accounts:
  message: "Welcome to mad accounts - prod app"
  contact:
    name: "Mad - Accounts - CEO"
    email: "mad@mad.com"
  support:
    - (566)643-3568
    - (566)643-3569